# Generated by Django 4.2 on 2023-04-25 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='authorUser',
        ),
    ]
