# Generated by Django 4.2 on 2023-05-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_author_author_authoruser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dateCreation']},
        ),
    ]
